branches:
  only:
  - master
language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq optipng
- sudo apt-get install -qq --no-install-recommends asciidoc
- git submodule update --init --recursive
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/share/asciidoc/asciidocapi.py
  ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi
- pip install -r requirements.txt
script: make publish
notifications:
  email:
    on_success: never
    on_failure: always
after_success: bash deploy.sh
env:
  global:
    secure: Xlxy3Yv2eeezOiqOUJzHuAyKhr642hCoGD+IgrahZIqo7GeMk13hMro5H6wjIiQK+QLO8srlNUih0SlMMzzPHEUvo3x8ipLKWbABns7jRvvq+rvvBZ8ujrgXreg1+L8PVUpXwBXX8gU/tUZ4tIt0A6rxgqZOeT+2Jn3Mv/x3xkQ=
